### ISSUE TITLE
Custom Build

### ISSUE THREAD

**Issue by Transwarpcom** [A-JiuA/WSAOnWin10#16]
### Target CPU architecture of WSA

x64

### WSA Release Channel

Release Preview

### Root solution

KernelSU

### GApps brand

MindTheGapps

### Remove Amazon

- [X] Remove Amazon

**Comment by Transwarpcom** [comment]
Opps, it might have some problems, can you try to fix it? Thanks a lot.

**Comment by A-JiuA** [comment]
WSA has switched from EROFS to EXT4 since 2306, but MagiskOnWSALocal haven't merged it yet. I'll run an Action for you

**Comment by A-JiuA** [comment]
https://github.com/A-JiuA/WSAOnWin10/actions/runs/5715559066
It should be OK

**Comment by Transwarpcom** [comment]
> > 
> 
> Thanks！！！

By the way, what improvements did you make to make it build successfully

**Comment by Transwarpcom** [comment]
> It's a custom command `cd MagiskOnWSALocal && gh pr checkout 620` . I haven't add it in issue template [LSPosed/MagiskOnWSALocal#620](https://github.com/LSPosed/MagiskOnWSALocal/pull/620)

Thank
