### ISSUE TITLE
[Bug] I am unable to install the module for the mask

### ISSUE THREAD

**Issue by tcy980909** [A-JiuA/WSAOnWin10#21]
### Describe the bug

After installing the module every time, the module will disappear after restarting WAS

### Steps to reproduce

1. install module
2. Restart WAS
3. Module disappears

### Expected behaviour

Normal module installation

### System (please complete the following information)

Version: [e.g. 22H2]
Build: [e.g. 19045.3208]
WSA Version: [e.g. 2305.40000.6.0]

WSA_2309.40000.8.0_x64_Release-with-magisk-26.3-MindTheGapps-13.0.zip

**Comment by tcy980909** [comment]
安装的这个版本的一件部署：WSA_2309.40000.8.0_x64_Release-with-magisk-26.3-MindTheGapps-13.0.zip

所有功能正常使用，在运行面具过程中尝试安装LSP管理器，数次安装重启后模块都会消失，怀疑是系统架构和模块的架构不同导致的

尝试用MT管理器在目录 /data/adb/modules/ 新建文件夹后重启WAS， 面具的模块页此时能识别到新目录，由此排除缺少权限所导致的故障

目前看来有可能无解

**Comment by A-JiuA** [comment]
无法解决这个问题，如果一定要用Magisk的话可以退回到旧版本

**Comment by A-JiuA** [comment]
2306版本应该可以，其余的需要你自己测试

**Comment by tcy980909** [comment]
> 2306版本应该可以，其余的需要你自己测试

好的 非常感谢您的回复
