### ISSUE TITLE
Asking about DLLs

### ISSUE THREAD

**Issue by YT-Advanced** [A-JiuA/WSAOnWin10#39]
Hello, today I just found out your interesting repository xD
So I am here to ask if I can use your DLLs from your repository for my WSA-Script repository. Thanks and hope you have a nice day !

Also do you want to be a collaborator of my repos UwU

**Comment by A-JiuA** [comment]
Thank you for your interest in this repository. You are welcome to use DLLs.
As for collaboration, I appreciate the offer! Although I may not have time to contribute as a collaborator actively, I'd be happy to assist you.

**Comment by YT-Advanced** [comment]
> As for collaboration, I appreciate the offer!

I have sent invitation to you :D
